github_data:
  open_issues:
    label: Open Issues
    search: is:open org:wp-cli is:issue sort:updated-desc
  open_issues_no_label:
    label: Open Issues Without Label
    search: is:open org:wp-cli is:issue sort:created-desc no:label
  open_issues_label_bug:
    label: Open Bugs
    search: is:open org:wp-cli is:issue sort:created-desc label:bug
  open_issues_good_first_issue:
    label: Good First Issues
    search: is:open org:wp-cli is:issue sort:created-desc label:good-first-issue
  open_pull_requests:
    label: Open Pull Requests
    search: is:open sort:updated-desc org:wp-cli is:pr
  open_pull_requests_awaiting_review:
    label: Open Pull Requests Awaiting Review
    search: is:open sort:updated-desc org:wp-cli is:pr team-review-requested:wp-cli/committers
github_repositories:
  - wp-cli/automated-tests
  - wp-cli/ability-command
  - wp-cli/admin-command
  - wp-cli/block-command
  - wp-cli/cache-command
  - wp-cli/checksum-command
  - wp-cli/config-command
  - wp-cli/core-command
  - wp-cli/cron-command
  - wp-cli/db-command
  - wp-cli/dist-archive-command
  - wp-cli/doctor-command
  - wp-cli/embed-command
  - wp-cli/entity-command
  - wp-cli/eval-command
  - wp-cli/export-command
  - wp-cli/extension-command
  - wp-cli/find-command
  - wp-cli/i18n-command
  - wp-cli/import-command
  - wp-cli/language-command
  - wp-cli/maintenance-mode-command
  - wp-cli/media-command
  - wp-cli/package-command
  - wp-cli/php-cli-tools
  - wp-cli/profile-command
  - wp-cli/restful
  - wp-cli/rewrite-command
  - wp-cli/role-command
  - wp-cli/scaffold-command
  - wp-cli/scaffold-package-command
  - wp-cli/search-replace-command
  - wp-cli/server-command
  - wp-cli/shell-command
  - wp-cli/super-admin-command
  - wp-cli/widget-command
  - wp-cli/wp-cli
  - wp-cli/wp-cli-bundle
  - wp-cli/wp-cli-dev
  - wp-cli/wp-cli-tests
  - wp-cli/wp-cli.github.com
  - wp-cli/wp-config-transformer
  - wp-cli/wp-super-cache-cli
